micronaut:
  application:
    name: micronautCrud
#  security:
#    intercept-url-map:
#      - pattern: /*
#        access:
#          - isAuthenticated()
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.fmi.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true